package weather;

/**
* weather/TempGeneratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from weather.idl
* 4 апреля 2022 г. 23:59:53 MSK
*/

public final class TempGeneratorHolder implements org.omg.CORBA.portable.Streamable
{
  public weather.TempGenerator value = null;

  public TempGeneratorHolder ()
  {
  }

  public TempGeneratorHolder (weather.TempGenerator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = weather.TempGeneratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    weather.TempGeneratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return weather.TempGeneratorHelper.type ();
  }

}
