package weather;


/**
* weather/TempGeneratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from weather.idl
* 4 апреля 2022 г. 23:59:53 MSK
*/

public interface TempGeneratorOperations 
{
  double generate (String s);
} // interface TempGeneratorOperations
