package weather;


/**
* weather/TempGenerator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from weather.idl
* 4 апреля 2022 г. 23:59:53 MSK
*/

public interface TempGenerator extends TempGeneratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TempGenerator
