package weather;


/**
* weather/TempGeneratorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from weather.idl
* 4 апреля 2022 г. 23:59:53 MSK
*/

public abstract class TempGeneratorPOA extends org.omg.PortableServer.Servant
 implements weather.TempGeneratorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("generate", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // weather/TempGenerator/generate
       {
         String s = in.read_string ();
         double $result = (double)0;
         $result = this.generate (s);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:weather/TempGenerator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TempGenerator _this() 
  {
    return TempGeneratorHelper.narrow(
    super._this_object());
  }

  public TempGenerator _this(org.omg.CORBA.ORB orb) 
  {
    return TempGeneratorHelper.narrow(
    super._this_object(orb));
  }


} // class TempGeneratorPOA
